function ReactDomClient(){
    return(
        <div className="Main">
            <h2>React Dom Client</h2>
            <p>Create a React root for the supplied container and return the root. The root can be used to render a React element into the DOM with render:
            createRoot accepts two options:

onRecoverableError: optional callback called when React automatically recovers from errors.
identifierPrefix: optional prefix React uses for ids generated by React.useId. Useful to avoid conflicts when using multiple roots on the same page. Must be the same prefix used on the server.
The root can also be unmounted with unmount:

hydrateRoot accepts two options:

onRecoverableError: optional callback called when React automatically recovers from errors.
identifierPrefix: optional prefix React uses for ids generated by React.useId. Useful to avoid conflicts when using multiple roots on the same page. Must be the same prefix used on the server.
            </p>
        </div>
    );
}

export default ReactDomClient;